micronaut:
  server:
    port: 10030
  application:
    name: mnhttpclient
netty:
  default:
    allocator:
      max-order: 3

github:
  organization: micronaut-projects
  repo: micronaut-core
  # the following must be set for the GithubFilter to be used but aren't required for the URLs the app accesses & aren't genuine
  #username: manholecover
  #token: ajfkldjfalkdjal